### PR TITLE
Update gtfs-lib to 4.3.5

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

Bump gtfs-lib to [v4.3.5](https://github.com/conveyal/gtfs-lib/releases/tag/v4.3.5).

### CODE REVIEW

**Comment by abyrd** [comment]
Hi @landonreed I'm frequently getting requests to review pull requests on various projects as a member of the @conveyal/employees team. Are these requests generated by an automated process? Could you switch to making requests to individuals?

Especially on gtfs-lib this can be confusing because it's hard to tell upon receiving a message whether a PR includes only data tools-specific changes, or it's a genuine request for review.

**Comment by evansiroky** [comment]
@abyrd, you're probably getting the notifications due to this file being in the repo: https://github.com/conveyal/datatools-server/blob/dev/.github/CODEOWNERS

**Comment by abyrd** [comment]
Thanks @evansiroky, yes, that must be what's controlling it. Can you change the CODEOWNERS file on the data tools projects to the IBI team, or to just you and @landonreed?

Just some side commentary - the grammar of the email notifications this produces (on several different projects) is kind of confusing: `@landonreed requested review from @conveyal/employees on: #235 Fix issue w empty fare_attributes#transfers val as a code owner.` Because it's not clear that the "as a code owner" text is automatically generated (as opposed to part of the commit message), and what it refers to: landonreed as a code owner? requested as a code owner? conveyal/employees as a code owner? transfers val as a code owner? For I while I was interpreting it as the last one.

**Comment by landonreed** [comment]
@abyrd and @evansiroky, for any repos transferring to IBI, let's just handle that by going ahead with the transfer. For gtfs-lib, do we want to change the code owners to the IBI team? We could also just remove code owners for that project to avoid notifying people but not explicitly setting IBI as code owners (not that that designation is very substantive).

**Comment by evansiroky** [comment]
I vote for the transfer and only allowing you and me as code owners.

**Comment by abyrd** [comment]
I'm not sure just transferring the project to a new organization will change the behavior. I see that datatools-server is under the ibi-group org but still has `* @conveyal/employees` in `.github/CODEOWNERS`. I think you'd need to update that line to reference a team at IBI, or simply `* @landonreed @evansiroky`.

For a project like gtfs-lib that we'll continue to work on collectively, I think we just need a slightly more elaborate CODEOWNERS file. Note that the first item on each line is a file pattern followed by one or more owner usernames. So we can designate multiple people as owners of specific packages, e.g. `/src/main/java/x/ @landonreed @evansiroky`.

**Pull request merged**
